[tool.poetry]
name = "ts"
version = "0.1.0"
description = ""
authors = ["Pranav Jha <pranavjha1993@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
torch = "^2.5.1"
statsforecast = {extras = ["plotly"], version = "^2.0.0"}
statsmodels = "^0.14.4"
mlforecast = "^1.0.0"
neuralforecast = "^1.7.6"
hierarchicalforecast = "^0.4.3"
utilsforecast = "^0.2.10"
datasetsforecast = "^1.0.0"
ipykernel = "^6.29.5"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
