# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/classifications/classification.process.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/classifications/classification.process.ipynb 1
import numpy as np
import pandas as pd
import torch
from datasetsforecast.m4 import M4
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from tqdm.notebook import tqdm

tqdm.pandas()
