# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/src/model.nlinear.ipynb.

# %% auto 0
__all__ = ["device"]

# %% ../../nbs/src/model.nlinear.ipynb 2
import pandas as pd
import pytorch_lightning as pl
import torch
import torch.nn as nn

# %% ../../nbs/src/model.nlinear.ipynb 3
device = "cuda" if torch.cuda.is_available() else "mps" if torch.mps.is_available() else "cpu"
